# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zfs_root/nixos";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "zfs_root/nixos/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zfs_root/userdata/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zfs_root/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "zfs_root/nixos/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "zfs_root/nixos/var/lib/docker";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
